# --- Identification SonarQube Cloud ---
sonar.organization=siretnathan-neet
sonar.projectKey=SiretNathan-neet_app-front
sonar.projectName=BobApp - Front-end

# --- Perimetre analyse ---
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts,src/test.ts,src/polyfills.ts,src/environments/**
sonar.sourceEncoding=UTF-8

# --- Couverture : rapport lcov genere par Karma ---
sonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info
sonar.coverage.exclusions=src/main.ts,src/environments/**,src/test.ts,src/polyfills.ts

# --- Le job echoue si la Quality Gate echoue ---
sonar.qualitygate.wait=true
